version: "3.0"

services:
  main:
    container_name: blog
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
      - 9229:9229
    command: npm run start:dev
    restart: always
